### ISSUE TITLE
Input text doesn't exist

### ISSUE THREAD

**Issue by MSGhero** [haxeui/haxeui-flixel#11] opened 2018-01-18 01:37 UTC
~~Creating a new TextField object will cause a crash.~~ Input text isn't well-handled by flixel yet.

**Comment by ianharrigan** [comment] 2018-01-18 08:25
Why a crash? Should it just display non editable text?

**Comment by MSGhero** [comment] 2018-01-18 16:46
Bc I haven’t added it in yet :P it’s on my list

**Comment by ianharrigan** [comment] 2018-01-18 17:10
gotcha

**Comment by greysondn** [comment] 2019-03-06 12:14
```
TypeError: Error #1034: Type Coercion failed: cannot convert haxe.ui.events::FocusEvent@8f6b269 to haxe.ui.events.MouseEvent.
	at haxe.ui.util::EventMap/invoke()[C:\HaxeToolkit\haxe\lib\haxeui-core\git\haxe\ui\util\EventMap.hx:70]
	at haxe.ui.core::Component/dispatch()[C:\HaxeToolkit\haxe\lib\haxeui-core\git\haxe\ui\core\Component.hx:1008]
	at haxe.ui.core::InteractiveComponent/set_focus()[C:\HaxeToolkit\haxe\lib\haxeui-core\git\haxe\ui\core\InteractiveComponent.hx:42]
	at haxe.ui.components._TextField::Events/onMouseDown()[C:\HaxeToolkit\haxe\lib\haxeui-core\git\haxe\ui\components\TextField.hx:285]
	at haxe.ui.util::EventMap/invoke()[C:\HaxeToolkit\haxe\lib\haxeui-core\git\haxe\ui\util\EventMap.hx:70]
	at haxe.ui.core::Component/dispatch()[C:\HaxeToolkit\haxe\lib\haxeui-core\git\haxe\ui\core\Component.hx:1008]
	at haxe.ui.core::Component/_onMappedEvent()[C:\HaxeToolkit\haxe\lib\haxeui-core\git\haxe\ui\core\Component.hx:1017]
	at haxe.ui.backend::ComponentBase/onMouseEvent()[C:\HaxeToolkit\haxe\lib\haxeui-flixel\git\haxe\ui\backend\ComponentBase.hx:291]
	at MethodInfo-4567()[C:\HaxeToolkit\haxe\lib\haxeui-flixel\git\haxe\ui\backend\ComponentBase.hx:247]
	at flixel.input.mouse::FlxMouseEventManager/update()[C:\HaxeToolkit\haxe\lib\flixel\git\flixel\input\mouse\FlxMouseEventManager.hx:548]
	at flixel::FlxGame/update()[C:\HaxeToolkit\haxe\lib\flixel\git\flixel\FlxGame.hx:738]
	at flixel::FlxGame/step()[C:\HaxeToolkit\haxe\lib\flixel\git\flixel\FlxGame.hx:670]
	at flixel::FlxGame/onEnterFrame()[C:\HaxeToolkit\haxe\lib\flixel\git\flixel\FlxGame.hx:538]
```

I can only assume that goes here.

**Comment by ianharrigan** [comment] 2019-03-06 12:57
This is just the flash target right? Something very strange is going on with that specific issue, cant quite understand it (especially as other haxe targets are fine):

https://github.com/haxeui/haxeui-openfl/issues/36

**Comment by greysondn** [comment] 2019-03-06 13:59
Sincerely, I didn't try HTML5. Since my target is Flash for now and it's been, well, a bumpy road, I'm doing testing just in Flash. Which is a longwinded way of saying "Well, it's the Flash target, anyway."

I've put [a workaround in place for now for my own work that can be survived, I'm sure](https://github.com/greysondn/Consume/blob/greysondn-takeover/source/net/darkglass/consume/PlayState.hx#L70). By all means, if you think a fix is in, I'll try it at that point in time; don't be afraid to let me know.

**Comment by MSGhero** [comment] 2019-03-06 15:00
Maybe it’s because I don’t have the `default` case handled. I can add that, though.

**Comment by greysondn** [comment] 2019-03-06 16:03
It looks like I may have been mistaken on where this goes; if you want me to break it into a separate issue, I can.

Being said, all I did was create a text field and click on it. Literally. Once it had focus that error popped up in a window for me.

**Comment by ianharrigan** [comment] 2019-03-06 16:33
@greysondn - the issue is already covered here, no? https://github.com/haxeui/haxeui-openfl/issues/36

@MSGhero - i dont follow, what default case?

**Comment by greysondn** [comment] 2019-03-06 16:40
Ian, is haxeui-flixel using haxeui-openfl under the hood? Otherwise it appears matching errors in distinct projects. (Had to stop a moment XD)

**Comment by ianharrigan** [comment] 2019-03-06 16:47
Well, i dont think that error is specific to any backend, anything that uses flash really, so i presume in your project, if you dont use flash, there is no issue? 

Its a real head-scratcher as the _only_ haxe target that fails this way is flash... very strange indeed

**Comment by greysondn** [comment] 2019-03-06 17:12
| Target | Data |
|---|---|
| Emscripten | SDK not installed |
| Flash   | See Above |
| HTML5 | Doesn't crash or dump an error, also doesn't receive input/focus when tried |
| Neko  | (Hopefully) unrelated Build Errors |
| Windows | I don't have a compiler set up |

Air and Electron seem like a waste of time (should be the same as HTML5 and Flash, right?) ... Android, no build tools and no VM to hook ADB to... Not sure what more you'd want in terms of build targets here.

**Comment by MSGhero** [comment] 2019-03-08 00:36
I'll check this weekend, but I meant that a line in the stack trace is a switch on MouseEvent type, but if a focus event or something came in, it wouldn't be a handled case since there's no default.

**Comment by ianharrigan** [comment] 2019-05-31 08:02
This should be fixed now (finally!)

**Closed as completed** 2019-05-31 08:02 UTC
